a=4
b=3
suma=a+b
print("suma",suma)
resta=a-b
print("resta",resta)
multiplicacion=a*b
print("multiplicacion",multiplicacion)
division=a/b
print("division",division)
modulo=a%b
print("modulo",modulo)
exponente=a**b
print("exponente",exponente)